Misc fixes && improvements
crobibero/jellyfin-client-avalonia pull request #59
Opened 2022-11-25 14:30 UTC by sferhah

2022-11-25 14:48 UTC, crobibero commented
I apprecate all of the work youre doing but I highly suggest splitting this into seperate PRs so I can review easier

If that is too much work for this just keep it in mind for potential future PRs

2022-11-25 15:57 UTC, sferhah commented
Ok. I'll try to do that during the week-end.

2022-12-04 16:05 UTC, crobibero requested changes

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/ServerStateModel.cs
> +    required public Guid Id { get; init; }
```suggestion
    public required Guid Id { get; init; }
```

Fix ordering

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/ServerStateModel.cs
> +    required public string Name { get; set; }
```suggestion
    public required string Name { get; set; }
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/ServerStateModel.cs
> +    required public string Url { get; set; }
```suggestion
    public required string Url { get; set; }
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/UserStateModel.cs
> +    required public Guid Id { get; init; }
```suggestion
    public required Guid Id { get; init; }
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/UserStateModel.cs
> +    required public Guid ServerId { get; init; }
```suggestion
    public required Guid ServerId { get; init; }
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/UserStateModel.cs
> +    required public string Token { get; set; }
```suggestion
    public required string Token { get; set; }
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Pages/LoadingPage.xaml.cs
> +    protected override async void OnAppearing()
```suggestion
    /// <inheritdoc/>
    protected override async void OnAppearing()
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/UserStateModel.cs
> +    /// Gets or sets the server id the user belongs to.
```suggestion
    /// Gets the server id the user belongs to.
```

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Models/UserStateModel.cs
> +    /// Gets or sets the user id.
```suggestion
    /// Gets the user id.
```

`init` setters should not be part of the documentation

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/Services/StateStorageService.cs
> +        foreach (var user in state.Users.Where(x => x.ServerId == serverId).ToList())
```suggestion
        foreach (var user in state.Users.Where(x => x.ServerId == serverId))
```

`.ToList()` shouldn't be required here

2022-12-04 16:05 UTC, crobibero commented on src/Jellyfin.Maui/ViewModels/Login/LoginViewModel.cs
> +        await Task.Delay(2_000).ConfigureAwait(false);  // mock slow network
The mocked delay should only occur on a debug build

2022-12-13 15:01 UTC, crobibero commented
Closing in favor of https://github.com/crobibero/jellyfin-client-maui/pull/65

2022-12-13 15:01 UTC, closed without merging