1/2 Decoupling ViewModels & Abstractions from Maui (the objective is …
crobibero/jellyfin-client-avalonia pull request #72
Opened 2023-01-26 03:06 UTC by sferhah

1/2 Decoupling ViewModels & Abstractions from Maui (the objective is to create a separate project, platform agnostic, destined to be referenced by several types of projects: Maui, Xamarin, Avalonia, WinUi, Android native...etc.)

2023-01-27 14:38 UTC, crobibero requested changes

2023-01-27 14:38 UTC, crobibero commented on src/Jellyfin.Maui/Services/INavigationService.cs
> +    void EnableCollectionSynchronization(IEnumerable collection, object? context, Action<IEnumerable, object, Action, bool> callback);
I would move all of these to a new `ApplicationService` as they don't really have anything to do with navigation.

2023-01-27 14:38 UTC, crobibero commented on src/Jellyfin.Maui/Services/NavigationService.cs
> -    private Application _application = null!;
Revert below changes and change L13 to the following.
```
private readonly Application _application = Application.Current!;
```

2023-01-28 12:41 UTC, sferhah commented
I've just made another commit, tell me if it's ok for you. (I'm a git noob, I take no offense)

2023-01-28 13:57 UTC, sferhah commented
I've also fixed a frequent crash within the ServerSelectViewModel (Servers.ReplaceRange(state.Servers)).

Why do you need to call .ConfigureAwait(false) in your viewModels ? .ConfigureAwait(false) leaves the Ui thread, any subsequent call will need to be resynchronized with DispatchAsync.

2023-01-28 14:08 UTC, crobibero commented
> Why do you need to call .ConfigureAwait(false) in your viewModels ? .ConfigureAwait(false) leaves the Ui thread, any subsequent calls will need to be resynchronized with DispatchAsync.

I'm a backend developer and just playing with Maui to learn- it is very possible that I have it incorrect. My thinking was to do all processing off of the UI thread and then sync when complete

2023-01-28 14:38 UTC, crobibero commented
I don't see how changing `ConfigureAwait(false)` to `ConfigureAwait(true)` fixes the thread update, my understanding is that `SafeFireAndForget()` brings the task to another thread.

2023-01-28 14:38 UTC, crobibero commented on src/Jellyfin.Maui/Services/IApplicationService.cs
> +    /// <param name="action">he method to be executed by the dispatcher.</param>
```suggestion
    /// <param name="action">The method to be executed by the dispatcher.</param>
```

2023-01-28 14:38 UTC, crobibero commented on src/Jellyfin.Maui/Services/IApplicationService.cs
> +    /// <param name="action">he method to be executed by the dispatcher.</param>
```suggestion
    /// <param name="action">The method to be executed by the dispatcher.</param>
```

2023-01-28 14:38 UTC, crobibero commented on src/Jellyfin.Maui/Services/NavigationService.cs
> +    private Application _application = Application.Current!;
```suggestion
    private readonly Application _application = Application.Current!;
```

2023-01-28 14:57 UTC, sferhah commented
> I don't see how changing `ConfigureAwait(false)` to `ConfigureAwait(true)` fixes the thread update, my understanding is that `SafeFireAndForget()` brings the task to another thread.

You are right, I did not see the code signature of SafeFireAndForget (Never used that lib):

`public static void SafeFireAndForget(this ValueTask task, in Action<Exception>? onException = null, in bool continueOnCapturedContext = false)`

the default value of continueOnCapturedContext is false, I assumed it to be true like that of ConfigureAwait().

So in order for it to work, BaseContentPage<TViewModel> needs to explicitly set continueOnCapturedContext to true:

```
    protected override void OnNavigatedTo(NavigatedToEventArgs args)
    {
        ViewModel.InitializeAsync().SafeFireAndForget(continueOnCapturedContext: true);
        base.OnNavigatedTo(args);
    }
```

2023-01-28 15:02 UTC, sferhah commented
I've implemented your last suggestion (fix type), 

Anyway, let's keep the code as is. Not very important for now,  I'll try to implement Shell navigation for my next PR.

2023-01-28 15:23 UTC, crobibero commented
I'm fairly certain `EnableCollectionSynchronization` is supposed to update the collection on the UI thread as well

2023-01-28 15:33 UTC, crobibero approved these changes

2023-01-28 15:33 UTC, merged